#encoding: ISO-8859-1
title: "NCPC - Nordic Collegiate Programming Contest"
discord_link: https://discord.gg/8mDKWnBJUY

defaults:
  - scope:
      path: "ncpc2023"
    values:
      lastUpdate: "2023-10-09"
  - scope:
      path: "ncpc2024"
    values:
      lastUpdate: "2024-10-07"
  - scope:
      path: "ncpc2025"
    values:
      headerText: "NCPC 2025"
      lastUpdate: "2025-11-10"
      eventTime: "Saturday October 4th 2025 11:00-16:00 CEST (UTC+2)"
      title: "Nordic Collegiate Programming Contest 2025"
      year: 2025
  - scope:
      path: "ncpc2026"
    values:
      headerText: "NCPC 2026"
      lastUpdate: "2026-05-10"
      eventTime: "Saturday October 3rd 2026 11:00-16:00 CEST (UTC+2)"
      title: "Nordic Collegiate Programming Contest 2026"
      year: 2026

kramdown:
  parse_block_html: true

plugins:
  - jekyll-redirect-from
